name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Login Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 3: Obtener la fecha y hora actual
    - name: Get current timestamp
      id: date
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

    # Paso 4: Build y Push for image con tag basado en fecha
    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-html-image:latest
          ${{ secrets.DOCKER_USERNAME }}/my-html-image:${{ steps.date.outputs.timestamp }}

    # Paso 5: Configuration SSH
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    # Paso 6: Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Detener cualquier contenedor que esté usando el puerto 80
          CONTAINER_ID=$(docker ps -q --filter "publish=80")
          if [ ! -z "$CONTAINER_ID" ]; then
            echo "Deteniendo el contenedor que usa el puerto 80..."
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID  # Eliminar el contenedor detenido
          fi

          # Descargar la última imagen desde Docker Hub
          echo "Descargando la última imagen desde Docker Hub..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-html-image:latest

          # Descargar la imagen con el tag de la fecha y hora
          TIMESTAMP=${{ steps.date.outputs.timestamp }}
          echo "Descargando la imagen con tag ${TIMESTAMP}..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-html-image:$TIMESTAMP

          # Ejecutar el contenedor con la última imagen (latest) o la imagen de la fecha
          echo "Iniciando el contenedor con la imagen más reciente..."
          docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-html-image:latest
          # O si prefieres usar la imagen con el tag de fecha y hora:
          # docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-html-image:$TIMESTAMP
        EOF
