name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        IMAGE_TAG="my-html-image:latest"
        docker build -t kevinguaa28/$IMAGE_TAG .
        echo "Built Docker image with tag: latest"

    - name: Push Docker image
      run: |
        IMAGE_TAG="my-html-image:latest"
        docker push kevinguaa28/$IMAGE_TAG
        echo "Pushed Docker image with tag: latest"

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          sudo docker pull kevinguaa28/my-html-image:latest
          sudo docker stop $(sudo docker ps -q)  # Detener los contenedores existentes
          sudo docker rm $(sudo docker ps -aq)   # Eliminar los contenedores detenidos
          sudo docker run -d -p 80:80 kevinguaa28/my-html-image:latest
          echo "Deployed the latest image with tag: latest"
        EOF
